### ISSUE TITLE
dial:unexpected EOF in GO

### ISSUE THREAD

**Issue by hlalibe** [CryptoCompareLTD/streaming-guides#4]
Hello,

I successfully built your GO example under Windows. The only change I made is I replaced on line 112 YOUR-API-KEY with my API key (which I've tested in other programs).

When I run it from the windows command prompt, i receive the error message:
dial:unexpected EOF

Any idea ?

**Comment by konradstrachan** [comment]
Hi hlalibe,

Apologies we don't presently monitor the documentation repo for issues raised by users. Can you contact us via data@cryptocompare.com and we can look in to this?

Thanks,

**Comment by Khatkhat055** [comment]
- 

- [ ] 

- [ ] @### 

> ****
